name: Deploy Lambda and Infrastructure

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      LAMBDA_PACKAGE_PATH: terraform/lambda_pdfextractor.zip

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Setup uv
      uses: astral-sh/setup-uv@v1

    - name: Recreate virtualenv
      run: |
        uv venv .venv
        source .venv/bin/activate
        uv sync
    
    - name: Export requirements for chalice
      run: uv pip freeze > lambda/requirements.txt

    - name: Package Lambda with Chalice
      run: |
        source .venv/bin/activate
        cd ./lambda
        chalice package lambda-package --pkg-format terraform
        cd ..
        cp ./lambda/lambda-package/deployment.zip ${{ env.LAMBDA_PACKAGE_PATH }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.11.4

    - name: Terraform Init
      working-directory: terraform
      run: terraform init

    - name: Terraform Plan
      working-directory: terraform
      run: terraform plan -out plan.out

    - name: Terraform Apply (manual approval)
      working-directory: terraform
      run: |
        echo "Showing the Terraform Plan:"
        terraform show plan.out
        echo "Waiting for manual approval..."
        read -p "Apply this plan? (y/N) " choice
        if [ "$choice" = "y" ]; then
          terraform apply plan.out
        else
          echo "Terraform apply aborted."
          exit 1
